# Applying Machine Learning and Deep Learning to identify home appliances consuming excess power

## Copyright (c) 2018, Faststream Technologies
## Author: Sudhanva Narayana

In [1]:
# Home Appliances Data
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Import Dataset
df = pd.read_excel('../../data/home.xlsx', sheet_name='Sheet3')

In [3]:
df.head()

  device weather_type           time  priority  order  out
0     AC     low cold  early morning         8     52    0
1     AC     low cold        morning         8     49    0
2     AC     low cold      afternoon         8     48    0
3     AC     low cold        evening         8     50    0
4     AC     low cold          night         8     51    0

In [31]:
df_group = df.groupby(['device', 'weather_type', 'time', 'priority', 'order']).mean()

In [32]:
df_group

                                                  out
device weather_type time          priority order
AC     cold         afternoon     11       66       0
                    early morning 11       70       0
                    evening       11       68       0
                    midnight      11       71       0
                    morning       11       67       0
                    night         11       69       0
       hot          afternoon     4        25       0
                    early morning 4        29       0
                    evening       4        27       0
                    midnight      4        30       0
                    morning       4        26       0
                    night         4        28       0
       low cold     afternoon     8        48       0
                    early morning 8        52       0
                    evening       8        50       0
                    midnight      8        53       0
                    morning       8        49       0
                    night         8        51       0
       low hot      afternoon     6        37       0
                    early morning 6        41       0
                    evening       6        39       0
                    midnight      6        42       0
                    morning       6        38       0
                    night         6        40       0
       very cold    afternoon     16       96       0
                    early morning 16       100      0
                    evening       16       98       0
                    midnight      16       101      0
                    morning       16       97       0
                    night         16       99       0
...                                               ...
Lights hot          afternoon     17       103      0
                    early morning 10       61       0
                    evening       14       85       0
                    midnight      1        4        0
                    morning       13       79       0
                    night         1        3        0
       low cold     afternoon     17       107      0
                    early morning 10       65       0
                    evening       14       89       0
                    midnight      1        8        0
                    morning       13       83       0
                    night         1        7        0
       low hot      afternoon     17       104      0
                    early morning 10       62       0
                    evening       14       86       0
                    midnight      1        6        0
                    morning       13       80       0
                    night         1        5        0
       very cold    afternoon     17       105      0
                    early morning 10       63       0
                    evening       14       87       0
                    midnight      1        12       0
                    morning       13       81       0
                    night         1        11       0
       very hot     afternoon     17       102      0
                    early morning 10       60       0
                    evening       14       84       0
                    midnight      1        2        0
                    morning       13       78       0
                    night         1        1        0

[108 rows x 1 columns]