In [2]:
# Home Appliances Data
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# Import Dataset
df = pd.read_csv('../data/home_data.csv')

In [4]:
df.head()

,device,building,floor,room,type,power,date,from_time,to_time,no_of_people,time_stayed_mins
0,AC,1,1,101.0,indoor,1363,2018-01-01,04:00:00,05:00:00,9,7
1,Computer,1,1,101.0,indoor,487,2018-01-27,08:00:00,09:00:00,0,17
2,Computer,1,1,101.0,indoor,464,2018-01-29,05:00:00,06:00:00,1,16
3,Computer,1,1,101.0,indoor,389,2018-01-30,01:00:00,02:00:00,8,27
4,Computer,1,1,101.0,indoor,338,2018-01-30,08:00:00,09:00:00,2,4

In [9]:
# Total Power Consumption on dates
df_date_group = df.groupby(['date', 'from_time', 'to_time', 'device', 'type', 'no_of_people']).sum()['power']
df_date_group

date        from_time  to_time   device    type     no_of_people
2018-01-01  00:00:00   01:00:00  AC        indoor   2               1568
                                                    5               1305
                                                    7               1439
                                                    8               1360
                                                    10              1161
                                           outdoor  2               3109
                                                    7               2531
            01:00:00   02:00:00  AC        indoor   6               1416
                                           outdoor  1               4192
                                                    4               9021
                                                    6               4487
                                                    8               2103
                                                    9               4050
            02:00:00   03:00:00  AC        indoor   4               1583
                                                    5               3469
                                                    8               1092
                                           outdoor  3               2281
                                                    5               4551
                                                    10              3163
            03:00:00   04:00:00  AC        indoor   2               1785
                                                    5               1875
                                                    7               2270
                                           outdoor  0               2678
                                                    5               4773
                                                    6               2313
            04:00:00   05:00:00  AC        indoor   0               3031
                                                    9               2658
                                           outdoor  2               2028
                                                    3               3167
                                                    8               4825
                                                                    ...
2018-01-31  19:00:00   20:00:00  Computer  indoor   10               424
                                           outdoor  1                328
                                                    7                384
                                                    8                687
                                                    9                410
                                                    10               339
            20:00:00   21:00:00  Computer  indoor   3                341
                                                    5                433
                                                    8                391
                                           outdoor  0                808
                                                    5                467
                                                    6                323
            21:00:00   22:00:00  Computer  indoor   2                851
                                                    3                325
                                                    6                394
                                                    7                463
                                                    8                342
                                           outdoor  7                356
            22:00:00   23:00:00  Computer  indoor   2                434
                                                    5                356
                                                    6                396
                                                    10               363
                                           outdoor  2                478
                                                    6                490
                                                    10               468
            23:00:00   00:00:00  Computer  indoor   7                440
                                                    10               682
                                           outdoor  5                864
                                                    6                383
                                                    10               481
Name: power, Length: 4595, dtype: int64